export const FAVORITE_ACTION = "app/favorite/FAVORITE_ACTION";
export const FAVORITE_ACTION_SUCCESS = "app/favorite/FAVORITE_ACTION_SUCCESS";
export const FAVORITE_ACTION_FAILED = "app/favorite/FAVORITE_ACTION_FAILED";
