export const LIST_CURRENT_USER_ACTION = "app/user/LIST_CURRENT_USER_ACTION";
export const LIST_CURRENT_USER_SUCCESS = "app/user/LIST_CURRENT_USER_SUCCESS";
export const LIST_CURRENT_USER_FAILED = "app/user/LIST_CURRENT_USER_FAILED";
